### ISSUE TITLE
Keys in place but handshake fails

### ISSUE THREAD

**Issue by snazzypants** [Brewskey/spark-server#104]
Sent particle keys doctor [devid] and keys appear to have sent successfully.  The photon restarts but blinks a very fast cyan with a red blink every so often.   On the local server:

> ::ffff:10.10.10.107 - - [29/Jan/2017:21:31:34 +0000] "POST /v1/provisioning/[devid] HTTP/1.1" 200 128 "-" "-"

> 
> Handshake failed:  error:0407109F:rsa routines:RSA_padding_check_PKCS1_type_2:pkcs decoding error { cache_key: '_64', deviceID: null, ip: '::ffff:10.10.10.117' }
> 1 : Core disconnected: Error: error:0407109F:rsa routines:RSA_padding_check_PKCS1_type_2:pkcs decoding error { cache_key: '_64', deviceID: '', duration: undefined }
> Connection from: ::ffff:10.10.10.117 - Connection ID: 64
> 
Connection ID increments about once every 2 seconds.

I can revert keys back to the default particle public keys, and the photon seems to work as normal (breathing cyan and connects to particle server just fine).  Not sure if this is related, but I also noticed that if I do a `particle identify` when config'd to the particle server, I get the normal device ID and firmware response, but if I do the same `particle identify` when config'd to the local server, I get device ID and 

> Serial err: Error: Opening COM3: Access denied
> Serial problems, please reconnect the device.
> Unable to determine system firmware version

**Comment by jlkalberer** [comment]
It sounds like you ran these two steps:
```
particle keys server ..\spark-server\default_key.pub.pem IP_ADDRESS
particle keys doctor your_core_id
```
When you weren't using the correct config. -- `particle keys doctor your_core_id`

If that isn't the case, you didn't run this step correctly:
```
particle config profile_name apiUrl "http://DOMAIN_OR_IP"
```

**Comment by snazzypants** [comment]
I ran:
```
particle config local apiUrl "http://10.10.10.10:8080"
particle config local
particle keys new
particle keys server device.pub.pem 10.10.10.10
particle keys doctor your_core_id
```
I'm pretty sure the config was pointed over to the local server because I could see it getting the other calls like GET /v1/devices and  POST /v1/device_claims.  It looks like the photon is trying to connect but gets the same handshake error every few seconds (this is also when the photon flashes red momentarily).  

> Handshake failed:  error:0407109F:rsa routines:RSA_padding_check_PKCS1_type_2:pkcs decoding error { cache_key: '_93', deviceID: null, ip: '::ffff:10.10.10.117' }
> 1 : Core disconnected: Error: error:0407109F:rsa routines:RSA_padding_check_PKCS1_type_2:pkcs decoding error { cache_key: '_93', deviceID: '', duration: undefined }
> Connection from: ::ffff:10.10.10.117 - Connection ID: 93
> >

**Comment by jlkalberer** [comment]
Ok, you don't need to run `particle keys new`. That will generate a new key for the device but it is not the server's key.

When the server starts up for the first time, it generates some server keys in `~/src/data/default_key.pub.der`. That's the key you need to use when setting up your devices.

**Comment by snazzypants** [comment]
Ah, OK, thanks! I had looked around for the key but for some reason didn't see that before :)

So I did the above with the proper keys and got this error when attempting to connect the photon to the local server (`particle setup`).  As well, the photon is now fast flashing cyan with 3 amber flashes every 20 seconds or so.

> ::ffff:10.10.10.10 - - [30/Jan/2017:05:44:03 +0000] "POST /v1/device_claims HTTP/1.1" 200 122 "-" "-"
> uncaughtException { message: 'this is not a typed array.',
>   stack: 'TypeError: this is not a typed array.\n    at Function.from (native)\n    at ChunkingStream._this._transform (C:\\node\\spark-server\\node_modules\\spark-protocol\\dist\\lib\\ChunkingStream.js:139:27)\n    at ChunkingStream.Transfor
> m._read (_stream_transform.js:167:10)\n    at ChunkingStream.Transform._write (_stream_transform.js:155:12)\n    at doWrite (_stream_writable.js:292:12)\n    at writeOrBuffer (_stream_writable.js:278:5)\n    at ChunkingStream.Writable.write (
> _stream_writable.js:207:11)\n    at Socket.ondata (_stream_readable.js:528:20)\n    at emitOne (events.js:77:13)\n    at Socket.emit (events.js:169:7)\n    at readableAddChunk (_stream_readable.js:146:16)\n    at Socket.Readable.push (_stream
> _readable.js:110:10)\n    at TCP.onread (net.js:523:20)' }

**Comment by jlkalberer** [comment]
If you follow the instructions in the readme, you don't need to run `particle setup`.  The device should have already been claimed when you run `particle keys doctor device_id`.

@AntonPuko - you have any idea about why it isn't being reclaimed?

**Comment by jlkalberer** [comment]
@snazzypants - did you get this resolved or are you still having issues?

**Comment by snazzypants** [comment]
Thanks for following up - I'm still having the same issue.  I tried updating spark-server and spark-protocol (since I saw that that referenced in the error message) but no change.  

PS. The error that I pasted in the last message (also copied below) is the same as what I get after sending `particle keys doctor device_id`.

> ::ffff:10.10.10.10 - - [31/Jan/2017:23:45:28 +0000] "POST /v1/provisioning/[devid]HTTP/1.1" 200 128 "-" "-"
> uncaughtException { message: 'this is not a typed array.',
>   stack: 'TypeError: this is not a typed array.\n    at Function.from (native)\n    at ChunkingStream._this._transform (C:\\node\\spark-server\\node_modules\\spark-protocol\\dist\\lib\\ChunkingStream.js:139:27)\n    at ChunkingStream.Transfor
> m._read (_stream_transform.js:167:10)\n    at ChunkingStream.Transform._write (_stream_transform.js:155:12)\n    at doWrite (_stream_writable.js:292:12)\n    at writeOrBuffer (_stream_writable.js:278:5)\n    at ChunkingStream.Writable.write (
> _stream_writable.js:207:11)\n    at Socket.ondata (_stream_readable.js:528:20)\n    at emitOne (events.js:77:13)\n    at Socket.emit (events.js:169:7)\n    at readableAddChunk (_stream_readable.js:146:16)\n    at Socket.Readable.push (_stream
> _readable.js:110:10)\n    at TCP.onread (net.js:523:20)' }

**Comment by AntonPuko** [comment]
@snazzypants could you tell please version of system firmware on your photon?

**Comment by jlkalberer** [comment]
Hey @snazzypants - turns out it was happening because we were using a newer version of Node APIs.  @AntonPuko switched to use older APIs so you should be good as long as you pull again.

**Comment by snazzypants** [comment]
Thanks! All seems well now (I'm still not completely sure what I'm doing or what to expect but my photon is now 'breathing' cyan as expected).

**Comment by jlkalberer** [comment]
Yeah, I think you should be good to go. Thanks for being a guinea pig :)
