### ISSUE TITLE
Removing device after _ensureWeHaveIntrospectionData error delays device from registering offline

### ISSUE THREAD

**Issue by wdimmit** [Brewskey/spark-server#110]
If I disconnect a device within a few seconds of seeing `_ensureWeHaveIntrospectionData error: Error: can't get describe data` the server will take several minutes to register the device as offline.  In the interim period, requests to read variables from the device time error out with a 400, but only after 15 seconds.  This is with the "coreRequestTimeout" setting set to 9000 (Changing it to 9000 from the default 30000 made no difference in this case).

(Devices have 0.6.0 FW)

**Comment by wdimmit** [comment]
I seem to be incorrect about the correlation between `_ensureWeHaveIntrospectionData error: Error: can't get describe data` and this issue.  I've just disconnected a couple of devices and had the 15 second waits before 400 errors for a couple of minutes each.  During this time, I was attempting to poll a variable on the device every 7.5 seconds - if that could be related.

Thanks,
Will

**Comment by jlkalberer** [comment]
I put out a diff today that I think will fix it. Anton needs to look it over but I'm pretty sure it works.

**Comment by AntonPuko** [comment]
@jlkalberer i think this can be closed?
