### ISSUE TITLE
Webhook variables not allowed in headers?

### ISSUE THREAD

**Issue by snazzypants** [Brewskey/spark-server#117]
On the particle cloud, I am able to pass variables to webhooks (requestType and headers).  When pointing to my local server, when I try to add below webhook, I get "Error wrong requestType". This is simple enough to change and it should be no problem for me to just hard code the request type. However I need to be able to send a variable Authorization token.  

Is this something that's changing with your project or am I just missing something? The webhook I'm trying to set up worked on the particle cloud before.

spark-server responds with: 
> webhookError: Error: Unauthorized

webhook:
```
{
  "event": "myevent",
  "url": "http://myapi.com/v1/{{path}}",
  "requestType": "{{request}}",
  "headers":
    {
        "Content-Type": "application/x-www-form-urlencoded",
        "Authorization": "{{api_key}}"
    },
  "responseTopic": "hook-response/api_{{SPARK_CORE_ID}}",
  "responseTemplate": "{{error}}:{{message}}",
  "form":
    {
        "var1": "{{var1}}",
        "value": "{{value}}"
    },
  "mydevices": true
}
```

**Comment by jlkalberer** [comment]
hi, we'll look into this. We implemented webhooks as a new feature so there will probably be bugs until this is stable.

**Comment by snazzypants** [comment]
Thanks for the quick response!  Changes work great. Just a quick FYI - originally I had the variable for the requestType all lower case (post) which threw an error (webhookError: Error: Unauthorized) on the local server when the webhook was invoked. I had to change the requestType variable to all caps (POST) and all worked fine.

**Comment by jlkalberer** [comment]
@AntonPuko - let's make this case insensitive

@snazzypants - No problem. Feel free to submit any other issues you find.

**Comment by AntonPuko** [comment]
ok.
@snazzypants should be good after merging that: https://github.com/Brewskey/spark-server/pull/120
