### ISSUE TITLE
Device connection problems: "pkcs decoding error" and "data too large for modulus"

### ISSUE THREAD

**Issue by lbt** [Brewskey/spark-server#124]
I've gotten myself a simple Docker image up and am trying to run this clone of spark-server inside it.

It's running but I get the errors pasted below. (note 2 devices here I think one is a core, one is a photon - I'll isolate later):

I have been running these devices quite happily using this single tweak to the old spark-server : https://github.com/lbt/spark-server/commits/lbt-working-master

So from an identical copy of that working setup (with the same core_keys/ and users/ files) I essentially checked out and ran the new code.
It starts with :
```
$ docker run -p 8080:8080 -p 5683:5683 spark-server 
Your device server IP address is: 172.17.0.2
Server started on port: 5683
express server started on port 8080

```
but then:
```
Connection from: ::ffff:10.0.0.102 - Connection ID: 189
Handshake failed:  error:0407109F:rsa routines:RSA_padding_check_PKCS1_type_2:pkcs decoding error { cache_key: '_189', deviceID: null, ip: '::ffff:10.0.0.102' }
1 : Device disconnected: Error: error:0407109F:rsa routines:RSA_padding_check_PKCS1_type_2:pkcs decoding error { cache_key: '_189', deviceID: '', duration: undefined }
Device startup failed: error:0407109F:rsa routines:RSA_padding_check_PKCS1_type_2:pkcs decoding error
Connection from: ::ffff:10.0.0.125 - Connection ID: 190
Handshake failed:  error:04065084:rsa routines:RSA_EAY_PRIVATE_DECRYPT:data too large for modulus { cache_key: '_190', deviceID: null, ip: '::ffff:10.0.0.125' }
1 : Device disconnected: Error: error:04065084:rsa routines:RSA_EAY_PRIVATE_DECRYPT:data too large for modulus { cache_key: '_190', deviceID: '', duration: undefined }
Device startup failed: error:04065084:rsa routines:RSA_EAY_PRIVATE_DECRYPT:data too large for modulus

```

I'm not an expert at nodejs so please let me know what you need to know.
Below is my annotated Dockerfile which defines the container - it should give you all the server info you need :)

I'm pretty sure the devices are on stock v0.6.0 firmware from a local build.

```
# Use the official nodejs v6.10.0 LTS container as a starting point
FROM node:boron

# Create an 'app' directory somewhere in the container
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies by copying in the package and using the preinstalled
# npm
COPY package.json /usr/src/app/
RUN npm install

# Bundle app source from outside the container to inside
COPY . /usr/src/app
# Do the babel thing to handle new features
RUN ./node_modules/.bin/babel src/ -d lib

# The access ports will be:
EXPOSE 8080 5683

# Now run the babel'ised main.js (is this the right command?)
CMD [ "node", "lib/main.js" ]

```

**Comment by AntonPuko** [comment]
Hi, @lbt.
I'm not sure about the second error, but the first `RSA_padding_check_PKCS1_type_2` usually means that you have incorrect `server keys` on devices.

Are you sure that you followed the setup instructions from the readme?
As I understand from your issue description, you just copied deviceKeys and users folders folder from your old server. Notice, that on the first start te server generates new server_key and you need to put it into your devices with `device keys server data/default_key.pub.pem <server ip>`

**Comment by lbt** [comment]
ah - that's a difference in the folder structure - thanks.
I updated my image to do
RUN mkdir -p /usr/src/app/data/deviceKeys/; cp /usr/src/app/default_key.* /usr/src/app/data/; cp /usr/src/app/core_keys/* /usr/src/app/data/deviceKeys/; cp -r /usr/src/app/users /usr/src/app/data/

and it's working :)

I've found another issue which I'll raise separately

Here is a docs PR which I hope will help: https://github.com/Brewskey/spark-server/pull/125
