### ISSUE TITLE
https

### ISSUE THREAD

**Issue by snazzypants** [Brewskey/spark-server#133]
Hi, I'm trying to set up spark server over a secure connection.  I tried changing the port from 8080 to 443 in the settings.js file but that seems to have broken everything - tried sending commands to  https://ipaddress:443 (+various permutations) but no luck. I think I've set up the SSL certificates properly but am not completely sure.

**Comment by jlkalberer** [comment]
Have you tweaked the server setup code to use [something like this](http://stackoverflow.com/questions/11804202/how-do-i-setup-a-ssl-certs-for-an-express-js-server)?

**Comment by snazzypants** [comment]
Thanks - works perfectly.
