### ISSUE TITLE
Webhook GET request with querystring

### ISSUE THREAD

**Issue by snazzypants** [Brewskey/spark-server#134]
I'm having trouble migrating a webhook from the particle server to the spark server; getting a return with "data": "Bad Request".  This is a GET request with a query string (I have another webhook with a POST request with form data that is working fine on spark server).

Originally I had put the query string the URL like:
"url": "http://api.com/endpoint?id={{id}}&value={{value}}"

I also tried
"url": "http://api.com/endpoint"
"qs": "id={{id}}&value={{value}}"

But am still getting a bad request error each time. Any idea?

**Comment by jlkalberer** [comment]
@AntonPuko can you look into this when you have some time?

**Comment by snazzypants** [comment]
OK...so after lots more banging my head against the wall, I don't think it's related to the query string. I've stripped my webhook down to the bare minimum and am having issues with GET requests.  I have set up identical GET and POST responses to this test endpoint url on my API server, which just returns a static response.

{
  "event": "test",
  "url": url,
  "requestType": "GET"
)

The above will return a bad request error (using GET); with POST, the webhook gets the response just fine.   It seems to be some kind of interaction with my API server - I can do GET requests to other public api's without error.  But again, the GETs to my server used to work on the particle cloud.

Not sure what to check next...do you guys have any ideas?

**Comment by jlkalberer** [comment]
I think this is going to be hard to repro without hitting your API. 

Can you make a dummy endpoint (GET) that we can test against and email `john-at-brewskey.com`?

**Comment by jlkalberer** [comment]
I think I've fixed it but there is a good possibility I introduced another bug @AntonPuko
