### ISSUE TITLE
[Not an issue] Help for debugging purpose.

### ISSUE THREAD

**Issue by straccio** [Brewskey/spark-server#149]
Hi, and good job.
I don't really know Babel, can someone help me to debug this project?

**Comment by straccio** [comment]
Solved with this guide.
https://www.youtube.com/watch?v=gxCCXXcqJfw

now i check how to use spark-protocol sources.

**Comment by jlkalberer** [comment]
Ahh.. you will probably need to hack on some things to make that work since we use the transpiled source (`dist` folder) when running `spark-protocol` in `spark-server`

**Comment by AntonPuko** [comment]
this should work:
1) setup the webstorm debugger for spark-server project, for node interperter choose ./node_modules/.bin/babel-node(.cmd for windows)
2) in spark-protocol: `npm link` and in package.json change main from `./dist/index.js` to `./src.index.js`
3) in spark-server: `npm link spark-protocol`
4) run the debugger

**Comment by straccio** [comment]
Tnx, now i can debug!

**Comment by straccio** [comment]
Can i contribute to this repository?

**Comment by jlkalberer** [comment]
Yeah, we'd love any additional help. What feature are you planning on building?

**Comment by straccio** [comment]
Actually i need to put the data outs from devices in an "abstract container".
The container can be Mongo DB or anything else (in this moment i think fluentd + kibana).
I'm building a smarthome with particle photons and other devices that they connect in the same way to spark-server.

Anyway i can help to add "cluster/balancing" features, i have done that several times with others programs using ZeroMQ or memcache to share resources inside and outside the "server" and keepalived to balance or distribute the load over a fleet.
