### ISSUE TITLE
Error loading user from TingoDB.

### ISSUE THREAD

**Issue by straccio** [Brewskey/spark-server#150]
I'm getting this error on every request.
`{"error":"server_error","error_description":"Server error: `accessTokenExpiresAt` must be a Date instance"}`

**Comment by AntonPuko** [comment]
Hm, can't reproduce. I've just checked with the fresh db: 1) created user 2) get token 3) do some requests. And it works okey.

Could you provide some more information? node version, os, steps to reproduce?

**Comment by jlkalberer** [comment]
@straccio - also list the node/npm version

**Comment by straccio** [comment]
After a clean install the problem gone.
Anyway:
node v6.10.2
npm v4.6.1

Tnx for your support.

**Comment by jlkalberer** [comment]
Did you run the migration script to populate your database? That's the only thing I can think of.

**Comment by straccio** [comment]
No.
I have cleaned and reinstalled all the dependencies and that solved the problem.
