### ISSUE TITLE
How to share /data between different servers?

### ISSUE THREAD

**Issue by snazzypants** [Brewskey/spark-server#152]
I've set up a load balancer with two spark-servers attached.  Commands to the devices are being routed through the load balancer.  I'm running into a problem where the device itself is connected to server1, but external requests are being split between server1 and server2. If the request goes into server2, it thinks the device is not connected.

I was thinking that a solution would be have server2 point to server1's data directory - is there any way to do this?

EDIT:
Thinking about this some more....don't think simply sharing the data folder would work, right?  I was playing around with the clustering options here https://github.com/Unitech/pm2 and was able to get multiple workers going.  But, the same problem....if I do a GET /v1/devices, the device will only report back as connected if the GET request was sent to the same fork that the device is really 'connected' to.  Is the app not stateless?

**Comment by jlkalberer** [comment]
This is why we've added database support.  I haven't tested our clustering fork but using the database should handle data between servers -- it does not yet handle events.

**Comment by jlkalberer** [comment]
So there are a few tasks left to move everything to the database -- after that #137 will handle communicating events.  If your app doesn't rely on devices communicating to each other, what we have currently should be good enough.
