### ISSUE TITLE
Transfer device ownership administratively

### ISSUE THREAD

**Issue by wdimmit** [Brewskey/spark-server#153]
To ease automation for some use-cases, it would be useful to be able to take ownership of a device as an "administrator" without requiring the original owner to release it first.

**Comment by jlkalberer** [comment]
That means we'd need to bake in roles. I'd be fine with adding an additional property to all accounts. You'd need to manually edit the database for now.

cc: @AntonPuko

**Comment by AntonPuko** [comment]
@wdimmit doest last dev with the admin account work and enaugh for you? Can we close the issue or need to add something else?

**Comment by jlkalberer** [comment]
Yeah, that would work if you do curl requests. I'm not sure how you would login with that user if you want to use the particle CLI

**Comment by AntonPuko** [comment]
nothing prevents your from login for that user from particle-cli and get one more token. Just that last token won't be infinite, but with the default expiration time.
