### ISSUE TITLE
Check DB for existing item before creating a new one

### ISSUE THREAD

**Issue by jlkalberer** [Brewskey/spark-server#156]
I can create multiple users with the same email right now. We should validate that there isn't an existing user before creating a new one.

I also see that I can claim the same device multiple times.

**Comment by AntonPuko** [comment]
No, you can't.
https://github.com/Brewskey/spark-server/blob/dev/src/controllers/UsersController.js#L28 check.

https://github.com/Brewskey/spark-server/blob/dev/test/UsersController.test.js#L30-L36 test
