### ISSUE TITLE
How to push OTA updates?

### ISSUE THREAD

**Issue by snazzypants** [Brewskey/spark-server#163]
I am able to push OTA updates to individual devices via the particle CLI, but I was wondering if there is a streamlined way of doing OTA updates for our to all connected devices with spark-server? Maybe something with the knownApps folder?

**Comment by jlkalberer** [comment]
I haven't tested it but that's what I'd suggest. I think you might need to tweak a json file that contains the known apps.

We will be needing this feature ourselves pretty soon so it will be worked on.

---

The way it will work is that when you upload a new version of the firmware, it will flash all connected devices. If any device isn't connected, it will do an auto-update as soon as it connects to the server.  

I don't have any solid dates for when this will be ready though.

**Comment by wdimmit** [comment]
@snazzypants For less critical updates and modest-size deployments, you can do one of the things I've done in the mean time.  It's simple, but requires adding a fwVersion variable your firmware.

Write a script that calls the `GET /v1/devices` endpoint of spark-server.  Filter out all the offline targets, then generate a list of devices needing updates by querying each of the online devices for it's fwVersion.  Then loop over this list hitting `PUT /v1/devices/:deviceId` (with the appropriate firmware).  Depending on your other settings, it may or may not be safe to force system firmware updates this way (sending a firmware compiled against 0.6.1 to a 0.6.0 device, for example).

If you cache the results of the query step to a file or database, the entire script can be run very quickly.  You could add the script to cron (or similar) and execute it routinely.  

Alternately, you could create a webhook that triggers on `spark/status`.  You could then immediately query the fwVersion variable on connect and issue an update if needed right after the device comes online.  You may still need the above script if your devices rarely restart.

Good luck.

**Comment by jlkalberer** [comment]
So I want to do it the same way that Particle does their updates. Not only does it do the application update --- it will also do the system updates.  So even if you put up a new fireware update that is 0.6.4 -- the old devices will get everything.  

I have this working as far as updates go but I need to get the offline to online updates working. 

Anyways, I do have some customers who shouldn't get the main firmware update and I plan on creating a version of "products" to make this happen.  

Depending on how much work I have to do in the next few weeks "my real job"  will depend on when I get all of this done.

**Comment by jlkalberer** [comment]
This has been resolved a long time ago
