### ISSUE TITLE
Toggle webhook logging

### ISSUE THREAD

**Issue by snazzypants** [Brewskey/spark-server#164]
Is there a way to toggle the webhook logging?  We utilize the webhooks kind of frequently and it clogs up the logs. I'm trying to troubleshoot a separate issue so it's kind of annoying. Tried the LOG_REQUESTS option in settings.js but that seems to only show/hide the http requests.  Thanks!

**Comment by jlkalberer** [comment]
yeah.  If you have the most recent verrsion I'll definitely be tweaking it.  I am just working on optimizing webhooks right now so I want to log it.

**Comment by jlkalberer** [comment]
This should be fixed now

**Comment by snazzypants** [comment]
@jlkalberer Thanks. I see there's been a lot of activity on the project recently. Would it be a good time to pull yet? 

I am running in production mode right now, so I'd like to be a little cautious, but would also be interested in the latest and greatest.  On my current servers, something happens where the devices will start to disconnect and reconnect constantly. They can still communicate OK, but are just constantly reconnecting. Restarting the server fixes it but the problem usually comes back after a couple hours. Only have ~30 devices on each server so I don't think it's the load problem mentioned in other threads.  The last time I pulled was pretty soon after the DB was implemented (just for deviceAttributes/users/webhooks, not keys).

Thanks.

**Comment by jlkalberer** [comment]
Yeah, we actually fixed that issue as well but I'd wait a little bit for testing.

Are you using MongoDB or the local DB?  We replaced the local DB because it had bugs and the DB would get corrupted after a while.

If you're seeing bad performance right now I'd recommend updating though.  I was running 2k virtual devices on a single server last night and it was working much better than that older branch.

**Comment by snazzypants** [comment]
I thought I was using MongoDB.  Went ahead and spun up a new instance with the latest dev branch just to play around. I tried to run the migrateFilesToDatabase.js script to migrate my keys over to the database but get the following error:

```
Setup database connection... 
[Error: Wrong database type]
```
...help?

**Comment by jlkalberer** [comment]
@antonpuko

**Comment by AntonPuko** [comment]
you should run the script with `mongo` argument. But better just do `npm run migrate-to-mongo` and don't forget to add URL prop in settings.DB_CONFIG.URL
