### ISSUE TITLE
oAuthClient.json not Copied to dist directory

### ISSUE THREAD

**Issue by haeferer** [Brewskey/spark-server#171]
Hi, 

first of all, very NICE WORK

right now i'm working on a complete Docker Image for hosting the Server. 
My goal is to create a complete Docker Image for running the Server including concept
to store RUNTIME Files etc. out of the box.

The current state works well (image is under 200mb), but with current Checkout it is not working well, cause it ends 

 ....Cannot find module './oauthClients.json'

I think  this is caused by a missing file in the /dist directory?

I will fix this inside the DockerScript by copying the existing File, i would also suggest to move this file to a different directory (like /data) (cause the data directory 
is the directory mapped outside from docker with all runtime informations from the image)

Nice Work, 

best regards

Andreas

**Comment by haeferer** [comment]
I've fixed this by using

"npm run build"

and starting with

node dist/main.js

now i get a "h5.coap not found"

 from the "node_modules/spark-protocol/dist/clients/Device.js:48:10"

maybe the problem is the dependecie "spark-protocol" is mapped to 

git+https://github.com/Brewskey/spark-protocol.git#dev

dev path?

**Comment by haeferer** [comment]
I will close this issue, cause right now there are a lot of changes going on ...

**Comment by jlkalberer** [comment]
Yeah, I think you might just need to update your `spark-server`.  I'm fairly certain that in some newer builds this is being copied over.
