### ISSUE TITLE
Update docker info

### ISSUE THREAD

**Issue by jlkalberer** [Brewskey/spark-server#181]
It's not 100% stable but I've removed the dependency on ursa which removes the need to compile with node-gyp + install openssl.

Can you update the docker setup and remove this stuff?

cc: @haeferer

**Comment by haeferer** [comment]
Yep, I will test this setup tomorrow. I will also test the different NODEJS / NPM Versions

If it works i will update the Docker File

**Comment by jlkalberer** [comment]
Cool.. again, this change hasn't been thoroughly tested so there might still be some issues where the server will crash.

We will be testing for stability (and trying to fix the no device data bug).

**Comment by haeferer** [comment]
I will make different Images including stable and nightly, so this will be a "nightly" image

**Comment by haeferer** [comment]
I've created a dockerhub [https://hub.docker.com/r/keatec/spark-server/](https://hub.docker.com/r/keatec/spark-server/) image.
As long as there are no version(releases) available i will maintain the following Tags

* __nighlty__ (latest version compiled)
* __latest__ (latest version known to be stable - from my side of view ;) )
* __CommitID__ (CommitID used to build the image)

**Comment by jlkalberer** [comment]
Thanks so much for doing this.
