### ISSUE TITLE
Question about Keys

### ISSUE THREAD

**Issue by haeferer** [Brewskey/spark-server#184]
I've just configured a new Particle without access to to Spark-Server

* Setting Server Port, Setting Public Key of Server (DFU)
* Generating Device Keys, Setting Device Key on Particle (DFU)

The "particle keys doctor" command fails at the end to publish the public key to the spark-server (cause its another network)

But the system works fine..

??? Is it needed to publish the PubliceKey File to the server or is the Particle
sending this Public-keyfile automatically ???

**Comment by jlkalberer** [comment]
This should like your `particle config someServerConfig` wasn't called before you called `particle keys doctor`

**Comment by haeferer** [comment]
No, was another Problem. There are so many particles right now in my office, i simply took the wrong one  :(
