### ISSUE TITLE
nonce decryption failing on Electron

### ISSUE THREAD

**Issue by steves2j** [Brewskey/spark-server#191]
When trying to Handshake with the Electron we are getting a Decryption failure at the nonce response.

Not quite sure what is going on and if NodeRSA has an issue with the mbed version PKCS#1 encryption using public keys.

> Stack:  Error: Error during decryption (probably incorrect key). Original error: Error: error:040A1079:rsa routines:RSA_padding_check_PKCS1_OAEP_mgf1:oaep decoding error
    at NodeRSA.module.exports.NodeRSA.$$decryptKey (/home/dev/spark-server/node_modules/node-rsa/src/NodeRSA.js:301:19)
    at NodeRSA.module.exports.NodeRSA.decrypt (/home/dev/spark-server/node_modules/node-rsa/src/NodeRSA.js:249:21)
    at CryptoManager.decrypt (/home/dev/spark-server/node_modules/spark-protocol/dist/lib/CryptoManager.js:164:36)
    at Handshake._callee4$ (/home/dev/spark-server/node_modules/spark-protocol/dist/lib/Handshake.js:294:61)
    at tryCatch (/home/dev/spark-server/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/home/dev/spark-server/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/home/dev/spark-server/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/home/dev/spark-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dev/spark-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at F (/home/dev/spark-server/node_modules/core-js/library/modules/_export.js:35:28)
    at Handshake.<anonymous> (/home/dev/spark-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at Handshake._readDeviceHandshakeData (/home/dev/spark-server/node_modules/spark-protocol/dist/lib/Handshake.js:342:20)
    at Handshake._callee2$ (/home/dev/spark-server/node_modules/spark-protocol/dist/lib/Handshake.js:179:26)
    at tryCatch (/home/dev/spark-server/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/home/dev/spark-server/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/home/dev/spark-server/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/home/dev/spark-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dev/spark-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)

Looking through the code I can see that there is a mixture of PKCS#1 private keys but PKCS#8 public keys. Not sure why this is done this way when the Particle Electron is only dealing with PKCS#1 type keys.

Is the use of RSA keys a Electron only thing and the Photon uses EC keys?

**Comment by jlkalberer** [comment]
See https://github.com/Brewskey/spark-protocol/issues/81

It shouldn't be super hard to add this but I want to use an ecc library that runs natively or pure js and doesn't used a compiled binary.

The decryption portion only happens once so using a js-based library won't affect performance that much.

**Comment by steves2j** [comment]
That's reliant on adding UDP services, which seems to me a bit scary on a Mobile network for reliability.
Lets say I want to keep using TCP and these RSA keys, what do you think would be the issue here? I've configured the Electron to use TCP over UDP and it seems to be receiving and encryption the nonce but the server is unable to decrypt it.

**Comment by jlkalberer** [comment]
Ahh.. I thought you were using the standard UDP protocol with the electron.

I'll look into this.

**Comment by steves2j** [comment]
Yeah I figured as much. Seems that the public key is expected to be a PKCS8 but the private key is a PKCS1. And the server is expecting a bit of both. I need to wait for a photon to be delivered and hook that up see what it does. It could be that the implementation used by the electron is different.

**Comment by AntonPuko** [comment]
@steves2j try with the last version, you may need manually remove old device key from the db or make provision again.

**Comment by jlkalberer** [comment]
Closed with #192

**Comment by steves2j** [comment]
Still have the same issue. Granted that the server now accepts the device and loads it but I'm getting a slightly different error
`Handshake failed: ,{},{"cache_key":"_10","deviceID":null,"ip":"::ffff:115.189.100.216"}
1 : Device disconnected: Error: Error during decryption (probably incorrect key). Original error: Error: error:0407109F:rsa routines:RSA_padding_check_PKCS1_type_2:pkcs decoding error,{"cache_key":"_10","deviceID":""}
Device startup failed: Error during decryption (probably incorrect key). Original error: Error: error:0407109F:rsa routines:RSA_padding_check_PKCS1_type_2:pkcs decoding error`

This is on a newly built server, so no device keys existed prior.

I've tried loading the Server DER file into the device both as PKCS1 and PKCS8 as well as a PKCS8 PEM file to no avail.

I don't think the electron really cares if the Server pub key is valid or not, it just encrypts the nonce with whatever.

Checking to see if maybe what is being sent via the air was failing or something I've hardcoded the nonce to be a static value, and can see it arriving at the particle correctly. The particle does produce a 256byte return excypted once but due to the random seed used to encrypt I can't seem to compare this to the same once encrypted using openssl.

Trying to get my head around lightssl_message_channel and handshake cpp file in the particle and see what it's using to encrypt this once. Wondering if something wierd is going on with a corrupt or buffer overrun on the public key and thus its not encrypting correctly. But then why would it work with the particle.io server.

Thoughts?

**Comment by steves2j** [comment]
Something to add that I've just noticed. When loading the cloud based public key, it is a lot larger, indicating that the key expected by the electron is of the wrong size from the server.
Upon further investigation, the Particle cloud based one is a pkcs8 2048bit key with a domain tagged onto the end.

So I've upped the server to generate a 2048bit key instead of the 1024bit with a domain put into it, and have loaded that into the electron. The key now looks a lot better from the debug output but still no luck with the server.

**Comment by jlkalberer** [comment]
This really makes me think that they are using a completely different type of key.  I'll try to get some time over the weekend to look at it.

**Comment by jlkalberer** [comment]
@steves2j - OK, like I suspected the Electrons are using EC keys based on some elliptical algorithms.  

I added support for these key types and if you run `particle keys doctor 3242342` it will upload the correct key to the server.

**At this time I only made it work for TCP which will use up a ton of data. If you want UDP you're going to have to implement it yourself -- I don't have time to do it.**

I've also updated the readme with how to use electrons.

**Comment by jlkalberer** [comment]
I take that back -- they only use elliptical keys with UDP. I think if you follow the instructions in the readme it will send the correct RSA key.

**Comment by sohil4932** [comment]
Hello,
We are facing a similar issue when we are trying to connect Electron with a local cloud. 

When we run particle keys doctor command, it is sending "ecc" key on cloud. While we run particle-collider and create device it is sending RSA key on cloud. 

We have chosen protocol as TCP as per README file.

**Comment by jlkalberer** [comment]
@sohil4932 - If I had to guess, it would be that Electron TCP support has been removed from the electron. https://community.particle.io/t/electron-tcp-firmware/21078/7

I haven't tested this since the 0.6.3 firmware.

**Comment by sohil4932** [comment]
Thank you for your reply. 
I modified some code of particle keys doctor command in particle-cli src. So now it is sending rsa key to server and able connect with our local server. Only it is dis-connecting and re-connecting at every minute.

**Comment by jlkalberer** [comment]
Ok, can you open up a new issue for this?
Please include any error logs from the server. That should help when debugging this.
