### ISSUE TITLE
Commit: 066f863 , Device Flash failed

### ISSUE THREAD

**Issue by haeferer** [Brewskey/spark-server#194]
particle flash failed using

```
particle flash <id> image.bin
```

Output 
```
attempting to flash firmware to your device 3d004b001051353338363333
Flash device failed.
Update failed: 'ChunkReceived' failed.
```

Logs from Particle: 

 ```
0000051474 [comm.sparkprotocol] WARN: starting file length 262144 chunks 512 chunk_size 512
0000051548 [comm.sparkprotocol] INFO: chunk
0000051548 [comm.sparkprotocol] INFO: chunk idx=0 crc=0 fast=0 updating=1
0000051548 [comm.sparkprotocol] WARN: chunk bad 0
```

Please note:

* the filesize for UserPart is around 80kb and is compiled against 0.6.2 
So this message looks like he is trying to load a SystemPart (1 or 2)

* Function was OK at Commit c182732cad6075354846f6034076fe987d599994

**Comment by jlkalberer** [comment]
Yep, this is a known issue. I haven't had time to fix the flasher since we moved off ursa.
