### ISSUE TITLE
Logs from Spark-Server

### ISSUE THREAD

**Issue by haeferer** [Brewskey/spark-server#195]
Right now i'm doing a lot of tests, including long running with more particles.

Maybe it's time to give to logging a little love ... ;)

can we pleace include at least a timestamp in front of each line (for instance Date.now()). It would be much easyer to automaticaly process logs from Test Runs.

At our own systems we use BUNYAN (https://www.npmjs.com/package/bunyan).
It's a simple and very powerfull concept which works very nice in docker and cloud sysstems and for automatic processing. 

In short, BUNYAN logs only JSON lines (predefined format) and the output is later transformed (out of node process using pipe) into readable / colored /filtered output. 

Also nice is the concept of not using a bunch of parameters to a log function, a bunyan log function has only 2 Parameter, technical information (Object) and a readeable string.

```
  log.info({deviceid: 233323, latestinfo: "", state: 1},'Device Connected);
```
this will be converted to a complete JSON output including machine,name, timestamp, sublogger etc. 

if you run a bunyan nodejs solution you will use 

```
  npm start | bunyan
```

to produce a readable layout.

Also it's very easy to include such loggings in automatic managed runtime enviroments 

What do you think about this.

(PS: you can see a sample under my rabbit branch [https://github.com/keatec/spark-server/tree/rabbit/examples/rabbit](https://github.com/keatec/spark-server/tree/rabbit/examples/rabbit). I currently test a Rabbit MQ Connector which is not build into the server)

**Comment by jlkalberer** [comment]
You can override any repository (even the logger) with constitute. You'd be able to do any type of logging you want.

I think adding a timestamp would be OK but I don't want to modify just for your use-case.

**Comment by haeferer** [comment]
Ok, i will follow your suggestion and try to change the logger. Thx for your support. 
Next days i will deep div into the "consitute" module and will start testing these concept next week.

Thx again, Have a nice weekday,

Andreas

**Comment by jlkalberer** [comment]
Yeah, doesn't look like we inject the logger with constitute -- I'll try to add it over the weekend.

**Comment by haeferer** [comment]
Thx a lot. Would  b great

**Comment by jlkalberer** [comment]
Ok, I updated with constitute but I think it needs more work to get to what you want. You'd need to go through the whole codebase and "bunionize" all the logger.log calls.  You'd then needs to update the way the loggers use constitute.

**Comment by haeferer** [comment]
I will first look into substitute and then try to change some thinks for myself. Stay tuned . Thx for you help

Andreas
