### ISSUE TITLE
MessageQueue Sample

### ISSUE THREAD

**Issue by haeferer** [Brewskey/spark-server#196]
Hi,

Under my fork i created a branch "rabbit" including an implementation of an interface to amessagequeue system

https://github.com/keatec/spark-server/tree/rabbit/examples/rabbit

Currently it's implemented as a connector (between RabbitMQ and SparkServer) based on the existing SparkServer API. 

Current State
* processes state to a GLOBAL_LOG queue
* processes events to different QUEUES
* able to handle more then ONE Sparkserver

Complete run on docker 
* one or more SparkServer as image
* RabbitMQ as image
* Connector as image

**Comment by jlkalberer** [comment]
This works I guess but a better solution will just be hooking into the events pipeline without the particle API. I think @AntonPuko will be handling that soon.

**Comment by haeferer** [comment]
Sounds good. Thx

**Comment by AntonPuko** [comment]
@haeferer I made a simple interface for you to get all events. See an example: https://github.com/Brewskey/spark-server/blob/dev/examples/eventProvider.js
