### ISSUE TITLE
Constitue Logger

### ISSUE THREAD

**Issue by haeferer** [Brewskey/spark-server#198]
Hi, 
Thx for helping me solving my logger problem. I've seen first implementation. Very nice. Timestamp is a big step forward (at least from my side).
 I've seen your implementation 

static _log(...params: Array<any>): Function {
    return Logger.container.constitute('LOGGING_FUNCTION')(...params);
  }

So right no, the Logger function is constituted on every call to the logger ?

What about a more efficient implementation inside the constructor, like 
replace the static function with.

  constructor () {
    Logger._log = Logger.container.constitute('LOGGING_FUNCTION');
  }

 So now the _log function is constituted just once and directly used later

**Comment by jlkalberer** [comment]
Go ahead and make a PR for this. It's more of a micro-optimization.

What you'll want to do for the logger you want is figure out a way to completely override the log function so that we aren't using chalk in your use-case

**Comment by haeferer** [comment]
Yup, i will do so (in the next days). 
I will first try to fully understand instantiation and use of logging. 
Next step will be changes to this

Andreas

**Comment by haeferer** [comment]
Closed, so far
