### ISSUE TITLE
using subLoggers

### ISSUE THREAD

**Issue by haeferer** [Brewskey/spark-server#206]
Im currently working to make the logger.js "redefinable" to later use bunyan as a logger (see PR)

One of the features bunyan uses a lot are child loggers, so you can differentiate between modules inside the log. 

To show this concept i've made a childLogger implementation (without bunyan) on the current codebase.
Using childLoggers also needs changes on calling / initializing the logger.

You can see the implementation in this DIFF

[https://github.com/keatec/spark-server/compare/dev...keatec:bunyan](https://github.com/keatec/spark-server/compare/dev...keatec:bunyan)

What do you think?

**Comment by jlkalberer** [comment]
Can you show me an example of what the logging output would look like? I'm trying to understand the benefits of using this format.

**Comment by haeferer** [comment]
yup, i will prepare a sample. Stay tuned

**Comment by haeferer** [comment]
You can say from which component (file) the log is coming. 
So there is no need to make Informations inside the logEntry to identify the origin of this log.

For instance you can not say ("Default admin accessToken" is logged by "PermissionManager"
Another good example are the log lines like 

```
null
```
a few commit before (right now you are not able at all to say, who has logged this line!)

Here is the sample, ( no connected devices, for a better sample i need a little more time => tomorrow)

```
[2017-06-19T13:29:23.206Z] startup ChildModuleLogger FirmwareCompilationManager.js was created
[2017-06-19T13:29:23.222Z] logger.js Logger EventsController.js was created
[2017-06-19T13:29:23.234Z] logger.js Logger WebhookLogger.js was created
[2017-06-19T13:29:23.411Z] logger.js Logger WebhookManager.js was created
[2017-06-19T13:29:23.414Z] logger.js Logger PermissionManager.js was created
[2017-06-19T13:29:23.590Z] DefaultLogger.js Logger default was created
[2017-06-19T13:29:23.591Z] main.js Logger MAIN was created
[2017-06-19T13:29:23.673Z] main.js Your device server IP address is: 192.168.1.116
[2017-06-19T13:29:23.675Z] main.js express server started on port 8080
[2017-06-19T13:29:23.703Z] PermissionManager.js Default admin accessToken: 25a189ac3f46974a1349fbf04750c8aad24b9517
```

sorry, no coloring  here (the module has the same font and color as the timestamp)

**Comment by jlkalberer** [comment]
If all you want is the filename why not do something like this:

```
function getCallerFilename() {
  try {
      var err = new Error();
      var callerfile;
      var currentfile;

      Error.prepareStackTrace = function (err, stack) { return stack; };

      currentfile = err.stack.shift().getFileName();

      while (err.stack.length) {
          callerfile = err.stack.shift().getFileName();

          if(currentfile !== callerfile) return callerfile;
      }
  } catch (err) {}
  return undefined;
}
```

I'd be OK with putting this on all loggers.

**Comment by haeferer** [comment]
If you execute this on all log-calls, this will be a problem. I would only execute (if i would include this) in case of errors or warnings (to include this information, if the logger was not correctly configured). 

I would only include this during construction of logger as a replacement of 
```
Logger.createModuleLogger(module);
```

Other possible solution must be to reduce the logging as much as possible, to avoid bottlenecks, which is not a good idea during production on individual servers (maybe more than one)

**If you think about production:**

If your logging is cost intensive any error or warning which is caused by badDevices/or ThumbDevices will put load on your server which ends up in more problems (propably)
So any logging should be as cost effective as possible (from my point of view).

Thats also a reason for bunyan, cause all filtering, colorizing etc. is done out of process by another system/process

Additionally there maybe also other Names then Filenames (if a component is constructed from different files). I've choosen filenames so it can be implemented as easy as possible. 
A (maybe) better solution would be component Loggers (but in your case a File = Component seems ok)

Andreas

**Comment by jlkalberer** [comment]
@AntonPuko - This is getting overly complicated. It might just make more sense to replace our logger with bunyan. What do you think?

**Comment by haeferer** [comment]
There is another problem with this solution. If you are using Promises or callbacks the "source" is not always definable (or at least complicated to lookup automatically)

**Comment by haeferer** [comment]
If you like,I will provide a sample implementation how Bunyan could fit (out of my current running Projects)

**Comment by durielz** [comment]
Why force using bunyan if anyone can override it via constitute?

**Comment by jlkalberer** [comment]
It would actually improve the logging situation quite a bit. Our homegrown solution isn't great and doesn't allow you to pick the verbosity you see.  It's either "all" or "everything except logger.log calls"

I think what people actually want to override would be what streams are logged to. Bunyan's extensibility would allow you to easily do whatever you want.

Is there another logger that you prefer? If so, I will figure out a way to make this generic so you don't have to use bunyan.

**Comment by durielz** [comment]
Ok, I got it. No Bunyan is my favourite one.

**Comment by haeferer** [comment]
Bunyan, some ideas : 

The easiest way to use bunyan at file level would be a logger libary to hold the central Loggerinstance (where you can configure streams etc.=

```
const logger = require('bunyan').createLogger({
    name: 'Main',
    level: (process.env.LOG_LEVEL !== undefined ? process.env.LOG_LEVEL : 'info')
});

export default function getLogger(name: string, object: string) {
     return logger.child({name: name, object: object})
}

```

getLogger will create a child logger. This logger is configured with additional information ("name" will override the "name" from original logger) The "object" (or any other name you want) are additional informations for this logger (and optional). For instance if you create a logger for using together with a device this can be the device id (as result the deviceid will be logged as object on every log call to this instance)
 

calling a logger is the same as you already know. 
So the existing logger will be work out of the box.

please remember, if you use bunyan the plain output from will be json. You need to "compile" this result using the bunyan-cli. (This also works for LogFiles, LogStreaming on azure or amazon etc.)

**Comment by AntonPuko** [comment]
@jlkalberer I have nothing against.

**Comment by haeferer** [comment]
I've you want to take a look, i started a first implementation under

https://github.com/keatec/spark-server/tree/bunyan

currently it should do the exakt same behaviour as original

**Comment by haeferer** [comment]
Done
