### ISSUE TITLE
package-lock.json is not up to date

### ISSUE THREAD

**Issue by haeferer** [Brewskey/spark-server#229]
"Bunyan and other packages missing" is based on an old package-lock.json file. 

As a first workaround, after git clone, remove this file!

**Comment by haeferer** [comment]
I think it's based on this

https://github.com/npm/npm/issues/16580#issuecomment-301973529

**Comment by AntonPuko** [comment]
just make sure that you recreate and commit fresh package-json.lock every time you change deps in package.json

**Comment by haeferer** [comment]
How do you force a recreate. Documentation of NPM means : done automatic during save install etc. 
But it doesnt work in my side. Which version of NPM do you use

**Comment by AntonPuko** [comment]
npm 5.0.4
1) rm -rf node_modules
2) delete package-lock.json
3) npm i
4) commit package-lock.json

**Comment by haeferer** [comment]
i think there is a problem with the current LTS Version of node (6.11.0) with NPM 3.10.10 :(
NPM 5 starts with node 8... (at least at the standard packages)

I will take a look into this.

**Comment by AntonPuko** [comment]
i guess npm 3.10 doesn't use package-lock.json at all, so it should affect older versions.

**Comment by haeferer** [comment]
i will check this in the evening on my Mac Installation.
Maybe the problem  was a mixup with the sparc-protocol bug
