### ISSUE TITLE
particle-cli "list" command incorrectly reports "No devices found"

### ISSUE THREAD

**Issue by wdimmit** [Brewskey/spark-server#233]
Particle CLI reports "No devices found" when `particle list` is run.  The following error is generated in the spark-server log at the time of the request:

`0|spark-se | {"name":"MongoDb.js","hostname":"arioioA","pid":42048,"level":50,"err":{"message":"cursor does not exist, was killed or timed out","name":"MongoError","stack":"MongoError: cursor does not exist, was killed or timed out\n    at queryCallback (/opt/ario/brewskey/node_modules/mongodb-core/lib/wireprotocol/2_6_support.js:112:23)\n    at /opt/ario/brewskey/node_modules/mongodb-core/lib/connection/pool.js:469:18\n    at _combinedTickCallback (internal/process/next_tick.js:73:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)"},"msg":"Run for Collection","time":"2017-07-03T19:29:18.870Z","v":0}
0|spark-se | {"name":"DevicesController.js","hostname":"arioioA","pid":42048,"level":40,"err":{"message":"Cannot read property 'map' of undefined","name":"TypeError","stack":"TypeError: Cannot read property 'map' of undefined\n    at DeviceManager._callee6$ (/opt/ario/brewskey/node_modules/spark-server/dist/managers/DeviceManager.js:257:47)\n    at tryCatch (/opt/ario/brewskey/node_modules/regenerator-runtime/runtime.js:65:40)\n    at GeneratorFunctionPrototype.invoke [as _invoke] (/opt/ario/brewskey/node_modules/regenerator-runtime/runtime.js:303:22)\n    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/opt/ario/brewskey/node_modules/regenerator-runtime/runtime.js:117:21)\n    at step (/opt/ario/brewskey/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)\n    at /opt/ario/brewskey/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13\n    at process._tickDomainCallback (internal/process/next_tick.js:135:7)"},"msg":"get devices throws error, possibly no devices found?","time":"2017-07-03T19:29:18.872Z","v":0}`

The {get}/v1/devices endpoint seems to work properly, however.  This was tested with the same normal user account that does have assigned devices in both cases.

**Comment by AntonPuko** [comment]
hm, I can't reproduce with my local mongo db and 1k devices. 
The issue could possibly because of: 
1) some wrong documents migration, so there is some infinite loop with not unique ids, when we do find(), but since it works with getDevices endpoint - idk 
2) amount of devices is so big, that default mongo timeout expires, but it should be handled in our case with { timeout: false } in find() options.

..So, i have no ideas, /cc @jlkalberer

**Comment by jlkalberer** [comment]
I used to have this issue with Azure Cosmos due to the query string that tried to use global replication.

The only other thing I can think of is that you might need to update the way you set up your database -- @AntonPuko made a change (you can see the new way to implement in the Azure example).

**Comment by jlkalberer** [comment]
@wdimmit - are you still seeing this one?
