### ISSUE TITLE
variables data lost on update device name

### ISSUE THREAD

**Issue by durielz** [Brewskey/spark-server#241]
Hi guys, if i update my device name using PUT /devices/:deviceId then I lose the variables attribute in the device attributes data. 
I think the problem is in the updateByID method in DeviceAttributeDatabaseRepository.js which gets undefined variables data

**Comment by jlkalberer** [comment]
So... in the public server variables/functions are not actually saved to the DB.  I am not sure what I like better :/

I'd love to hear other people's opinions on this.

Also, @AntonPuko - I've noticed that sometimes devices are added and don't have a name.  Can you make sure all code-paths for create/update always pass in a name? I would say "move it to the repository" but I think that isn't the correct place for it.

**Comment by AntonPuko** [comment]
@jlkalberer Hm, I can't reproduce the issue with `name` and can't find a place where it can be failed.
