### ISSUE TITLE
"get_device_variable_value" timeout

### ISSUE THREAD

**Issue by snazzypants** [Brewskey/spark-server#242]
I make several calls from my application to the spark server to retrieve variables by using:
`/v1/devices/[deviceid]/[variable_name]`

This works most of the time, but some small percentage of the time (maybe 5% ??), the response is:
`{"error":"Response timeout for event: spark-server/get_device_variable_value","ok":false}`

There are no errors or logged events on the spark-server when this happens.

On one particular page, I make 3 of these calls when the page is loaded; when this issue occurs, 1 or 2 have the error, and the others work fine.  I'll reload the page right away, then like 5 more times, and all works well.

Is this a known issue, or even better, something that can be fixed?

Thanks

**Comment by jlkalberer** [comment]
Is this right after you start up the device or is it just randomly happening when you make that call?

**Comment by snazzypants** [comment]
It just happens randomly for (I think) all devices, regardless of when the device starts up.

**Comment by jlkalberer** [comment]
OK and how many devices do you have connected. We might be able to use particle-collider to debug.

**Comment by snazzypants** [comment]
Only about 90 devices.

**Comment by AntonPuko** [comment]
@snazzypants did you try with the server version after that change https://github.com/Brewskey/spark-server/commit/4451e05e55a73678b471f748cf22c6b9d3dd6d97 and https://github.com/Brewskey/spark-protocol/commit/d5f36660b0aa5f021eed5472a564727a1bc27222 ? we may resolve the issue after that.

**Comment by snazzypants** [comment]
@AntonPuko Thanks for the suggestion.  I have been working off commit https://github.com/Brewskey/spark-server/commit/23e95117bf9c6b0f95ddc5b25a85abbc21b8ece4 from Jul 5th, so before the changes you mentioned.

Last night, I tried the most recent version of both spark-server and spark-protocol, but there was an issue with some of my webhooks - GET requests were not being recognized by the spark-server.  Nothing logged by the webhook logger, and no errors logged (I'm not 100% sure about the lack of error messages, I had a lot of POST webhooks coming in at the time and it was difficult to parse through the logs).  

I had spun up a new server and copied all of my db files (webhooks, users, deviceAttributes, & deviceKeys) to the new server.  As well, some of my webhooks use variable requestTypes,  and some use hard-coded request types.  All of my POST webhooks are set up as variables, and all my GET webhooks are set up hard-coded, not sure if that makes a difference.

Thanks

**Comment by jlkalberer** [comment]
We haven't made any changes to our webhooks although we did change the logger.

I currently have latest deployed to my server and webhooks are working fine.

**Comment by snazzypants** [comment]
Hmmm...thinking about this some more and it occurred to me that I had a similar problem a few months ago (with the GET requests not working). 

This was brought up in #134 and fixed with https://github.com/Brewskey/spark-server/commit/76efd9a158db01896f9e9c9c3875a19556f4abde

I was poking around and saw that WebhooksManager.js was changed in https://github.com/Brewskey/spark-server/commit/7d620b87cb8399f7a651db3fc2f9a54d78082005 (coincidentally, the very first commit after the one I had been using :))

Looking at the diffs it seems that there were some changes relevant to the issue.

Thanks again.

**Comment by AntonPuko** [comment]
ok, we made a fix for GET requests, try the new version and tell if you still have some issues.

**Comment by AntonPuko** [comment]
@snazzypants do you still experience the issue?

**Comment by snazzypants** [comment]
Thanks @AntonPuko .  I had rolled over to the newest version on 9/8, and things have been going well for the past week or so.  Webhooks are working well, and have not seen the timeout since.
