### ISSUE TITLE
subscribe requests before claim

### ISSUE THREAD

**Issue by durielz** [Brewskey/spark-server#244]
Hi guys, after the claim process with softap the device is claimed successfully but for all the subscribe requests i get: 
`device wasnt subscribed to event: the device is unclaimed`
It looks like the subscribe requests are processed before the claim...

**Comment by jlkalberer** [comment]
What softap are you using just so we have all the details?

**Comment by jlkalberer** [comment]
Ok, cool. 

This should be a pretty easy fix then.

**Comment by AntonPuko** [comment]
@durielz Try new version, a device should reconnect after softap claiming now.

**Comment by durielz** [comment]
yes your solution work. I found another one without having to disconnect the device:
in DeviceServer.js in function _onDeviceSubscribe if I move all code except 
`await device.hasStatus(DEVICE_STATUS_MAP.READY);` 
in the 
`process.nextTick(()=> {` 
it works as well but I don't know if it is the correct way...

**Comment by jlkalberer** [comment]
@antonpuko - check both and see which is cleaner

**Comment by AntonPuko** [comment]
@durielz ok, removing additional disconnect() is great, thanks.
