### ISSUE TITLE
Bind Class ProductsController Missing DeviceManager from list

### ISSUE THREAD

**Issue by steves2j** [Brewskey/spark-server#245]
The ProductController Class has a constructor with DeviceManager as the first argument however the defaultbindings is missing 'DeviceManager' in binding list as the first element.

**Comment by jlkalberer** [comment]
@AntonPuko can you get this one as well with your changes? It's a one line fix in `defaultBindings.js`

**Comment by jlkalberer** [comment]
@steves2j - I haven't tested any of this end to end.  Please let me know if everything works for you (after this bug is fixed)

**Comment by steves2j** [comment]
Also found that the ProductsController.js is missing an assignment to this._deviceManager = deviceManager in the constructor.

I really should setup a github fork of this project, and create proper pull request, its just that we are adding things into the core software that you may not need or want, and typically we use BitBucket over Github.

**Comment by jlkalberer** [comment]
What features are you adding?  As long as it matches the public cloud we're fine with PRs

**Comment by steves2j** [comment]
I've forked and committed my changes, so feel free to peruse.

Basically we are using electrons to communicate with the spark server, but want to reduce the amount of data passed back to the server. So have implemented an enhanced hogan library that now has the ability to substring so we can save between 50-100bytes per request as now the webhook can pick out sub parts of the string. 
I've implemented a types method in the webhook so that you can specify what the variable type is as some sites expect the json to contain a number and boolean instead of a string that represents this.

I've also added two switches that disables public account creations and disables global or top level event subscriptions.

**Comment by jlkalberer** [comment]
Ok, that makes sense.  I think that is pretty specific to your use case but disabling public accounts could be nice.

Are you planning on implementing UDP? That would save you a ton of data.

**Comment by steves2j** [comment]
At some point, unless you guys beat me too it :) . Currently we are only updating once an hour so over a month that is below the data cap on the service we are using. But in future we would need it.

Next thing we plan on implementing is a GUI for all the API interfaces Pretty generic to start with, then more specific later on, I think we'll implement it as a stand alone server, but may leverage the express server on the spark server to serve the static files, haven't decided yet.

**Comment by jlkalberer** [comment]
Hah... yeah, we aren't using electrons for anything so we most likely won't implement it.

A GUI would be great but we won't write that either (most likely). We have another node app that will implement things.
