### ISSUE TITLE
Fast-flashing cyan then one red flash and repeat

### ISSUE THREAD

**Issue by billbogaiv** [Brewskey/spark-server#263]
Running latest firmware on a photon, and confirmed running proper config via `particle config`. Just can't seem to get the photon to connect to the server. Just getting fast-cyan and one-red and repeat...

I can tell it's trying to connect to my local server since I can turn it off and the photon flashes a slower-paced cyan followed by a few orange flashes and repeat...

No additional info. is sent to the server console other than `INFO: DeviceServer.js/19940 on ...: Connected Devices (devices=0, sockets=0)`.

I did put the particle server keys back on the photon just to confirm it is not a device problem and it does connect to their server. Is there a different branch I could test?

**Comment by AntonPuko** [comment]
if you're trying to connect to local server you should see some error/not error logs for sure.
Your issue description looks like you still trying to connect to main particle server but with wrong server keys. Be sure that you set correct host when you do particle keys doctor:
`particle keys server ./data/default_key.pub.pem --host {your local IP}`

**Comment by billbogaiv** [comment]
I tried navigating through the server source to see if additional tracing/logging was output to a file, but came up empty. I'd just like to know if the server is even receiving a request and then go from there.

Do I need to run `particle device add {id}` or is that already part of the process following the steps in the README?

Is there a `particle` command to verify the key on the photon uses the expected server key? Or do I have to connect via serial and run some other command?

**Comment by billbogaiv** [comment]
Running `particle keys address` confirms the IP of my local server.

**Comment by AntonPuko** [comment]
1) confirm that you follow all steps described in this https://github.com/Brewskey/spark-server/issues/262#issuecomment-373546147 very carefully.
2) in `/src/settings.js` change `LOG_LEVEL` to `debug` and `SHOW_VERBOSE_DEVICE_LOGS` to `true`
3) the entry point for any device connection is there https://github.com/Brewskey/spark-protocol/blob/dev/src/server/DeviceServer.js#L210-L212 . So if there is any socket connection you should see at least `new connection` message on logs
4) It also can be some firewall or anything like that which is blocking your local connection to the IP...but if device doesn't get to the server at all it should behave a little differently: fast cayans, then 3 orange blinks and repeat... So try shut down the server, if the device changes its behavior from one red to 3 orange, it actually was trying to connect to local server.

**Comment by billbogaiv** [comment]
Ran:

```shell
➜  spark-server git:(dev) ✗ ./node_modules/.bin/update-firmware
Downloading cc3000-patch-programmer.bin...
Downloading cc3000-patch-programmer_1_14.bin...
Downloading core_doctor.bin...
Downloading core_tinker.bin...
Downloading deep_update_2014_06.bin...
Downloading doctor.ino...
Downloading electron_doctor.bin...
Downloading electron_tinker.bin...
Downloading p1_doctor.bin...
Downloading p1_tinker.bin...
Downloading photon_doctor.bin...
Downloading photon_tinker.bin...
Downloading tinker-usb-debugging-v0.4.8-rc.6-electron.bin...
Downloading voodoospark.bin...
Downloading system-part1-0.7.0-photon.bin...
Downloading system-part2-0.7.0-photon.bin...
Downloading system-part1-0.7.0-p1.bin...
Downloading system-part2-0.7.0-p1.bin...
Downloading system-part1-0.7.0-electron.bin...
Downloading system-part2-0.7.0-electron.bin...
Downloading system-part3-0.7.0-electron.bin...

Updated settings

Completed Sync
```

Trying to narrow down why `particle keys address` returns `tcp:<my-ip>:8080`. I can't seem to override the port. Any other IP (other than the server IP) allows me to configure the port. Or, am I way off base and that's the way it is supposed to work?

**Comment by AntonPuko** [comment]
the spark-spark actually runs two servers: 1) express server on port 8080 we server REST requests there 2) tcp server on port 5683 - its actully server for device connections.
so the issue is that you device is trying to connect to the express server.
when you do `particle keys server --host` - you `don't need to provide port`! put only ip there.
\

**Comment by billbogaiv** [comment]
When I run `particle keys doctor <my-photon-id>`:

```shell
[2018-03-29T23:43:29.152Z] DEBUG: app.js/18248 on xxx-xxx: request finish (req_id=fb7cd800-33aa-11e8-ae24-d3843df7f7ce, duration=1.529291, req.remoteAddress=::ffff:192.168.1.1, req.remotePort=50258)
    POST /inform HTTP/1.1
    host: xxx.xxx.xxx.xxx
    connection: Close
    user-agent: AirControl Agent v1.0
    content-type: application/x-binary
    content-length: 10968
    --
    HTTP/1.1 404 Not Found
    X-Powered-By: Express
    X-Request-Id: fb7cd800-33aa-11e8-ae24-d3843df7f7ce
    Access-Control-Allow-Origin: *
    Content-Type: text/plain; charset=utf-8
    Content-Length: 9
    ETag: W/"9-0gXL1ngzMqISxa6S1zx3F4wtLyg"
    Date: Thu, 29 Mar 2018 23:43:29 GMT
    Connection: close
[2018-03-29T23:43:35.052Z]  INFO: DeviceServer.js/18248 on xxx-xxx: Connected Devices (devices=0, sockets=0)
[2018-03-29T23:43:45.066Z]  INFO: DeviceServer.js/18248 on xxx-xxx: Connected Devices (devices=0, sockets=0)
[2018-03-29T23:43:55.070Z]  INFO: DeviceServer.js/18248 on xxx-xxx: Connected Devices (devices=0, sockets=0)
[2018-03-29T23:44:04.413Z] DEBUG: app.js/18248 on xxx-xxx: request finish (req_id=10802d60-33ab-11e8-ae24-d3843df7f7ce, duration=7.053821, req.remoteAddress=::ffff:192.168.1.137, req.remotePort=50548)
    POST /v1/provisioning/<my-photon-id> HTTP/1.1
    host: 192.168.1.137:8080
    content-type: application/x-www-form-urlencoded
    accept: application/json
    content-length: 470
    connection: close
    --
    HTTP/1.1 200 OK
    X-Powered-By: Express
    X-Request-Id: 10802d60-33ab-11e8-ae24-d3843df7f7ce
    Access-Control-Allow-Origin: *
    Content-Type: application/json; charset=utf-8
    Content-Length: 119
    ETag: W/"77-seCpAl3IVF1whldsPG2zN3zPCoA"
    Date: Thu, 29 Mar 2018 23:44:04 GMT
    Connection: close
[2018-03-29T23:44:05.072Z]  INFO: DeviceServer.js/18248 on xxx-xxx: Connected Devices (devices=0, sockets=0)
[2018-03-29T23:44:15.084Z]  INFO: DeviceServer.js/18248 on xxx-xxx: Connected Devices (devices=0, sockets=0)
```

**Comment by AntonPuko** [comment]
run `particle keys server ./data/default_key.pub.pem --host {ip}` without port.

**Comment by billbogaiv** [comment]
Well, long-story short, I don't know what the deal with my `particle-cli` code was. Did a fresh clone of `particle-iot/particle-cli#master`, ran the commands, and things are all set. Thanks for everyone's help.

**Comment by billbogaiv** [comment]
@jlkalberer: firmware is `0.7.0`.
