### ISSUE TITLE
Particle.subscribe for events published by CLI or via curl not getting to device

### ISSUE THREAD

**Issue by DaliborFarny** [Brewskey/spark-server#265]
Hello guys, thats me again ;-)

I am trying to publish events `eventName` to cloud and catch them on devices via Particle.subscribe(). When I publish the event from another device, all goes as expected. When I publish the same event from CLI or via curl from commandline, the device doesnt get it. When I listen for events via curl, I am getting all events - those published from CLI comes with "coreid":null.

This works (device-device)
This is how I subscribe on the listening device:
`Particle.subscribe("eventName", datahandler);`

This is how I publish event on the sending device:
`Particle.publish("eventName", publishString, 60, PRIVATE);`

This event goes through to the listening device:
event: eventName
data: {"coreid":"3f003d000747126562363230","data":"1234","published_at":"2018-05-22T08:10:41.238Z","ttl":60}

This event is never received by the listening device:
event: eventName
data: {"coreid":null,"data":"1234","published_at":"2018-05-22T08:10:42.686Z","ttl":60}

Help appreciated, thank you!

**Comment by DaliborFarny** [comment]
Thank you very much, I am just trying to test it on my side.. Pulled the updates, build it.. Then I set up new user, claimed one device for him and restarted the server to load new scripts.. It forgot the new user account (checking the database - there is just the admin account) and moreover, I cant claim the device under admin account as it is already claimed to that nonexisting account.
How can I permanently setup new user account?


—
Dalibor Farny

--- original message ---
On Tue, May 22, 2018 at 01:22 pm, <notifications@github.com> Anton Puko wrote:


There was a little bug, that public events weren't published as public when we do that with cli/curl. I fixed that.

Notice, that if you want to publish private event from cli/curl, you have to do that with the same user, which the target device claimed with.

So, now it should work for both cases, with public and private events.

—

You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by DaliborFarny** [comment]
@AntonPuko Have you commited the change already? The only edited file in last commit is packa.json-lock..

**Comment by AntonPuko** [comment]
yeah, the actual change was in spark-protocol https://github.com/Brewskey/spark-protocol/commit/96ccd9619e5f54917cf4f507ffd5d0fdb73a120e . for spark-server I only bumped a version of spark-protocol to the last commit... So you needto pull last spark-server and reinstall deps.

**Comment by AntonPuko** [comment]
About your users issues, that's very weird, it shouldn't delete any created users.

**Comment by DaliborFarny** [comment]
The user persists now even after restart. Going to update the spark protocol. Thanks

—
Dalibor Farny

--- original message ---
> Tue, 22 May at 2:21 PM, <notifications@github.com> wrote:


> About your users issues, that's very weird, it shouldn't delete any created users.

> —

> You are receiving this because you authored the thread.

> Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by jlkalberer** [comment]
@DaliborFarny - did you try logging in with `__admin__`/`adminPassword`? 

We create that default user if one doesn't exist.  I generally just use that account for managing devices.

**Comment by jlkalberer** [comment]
Cool @AntonPuko was seeing a OTA update loop on one of his devices so there still might be a bug. We'll fix as soon as we have a solid repro.

**Comment by DaliborFarny** [comment]
Hi @AntonPuko , I just wanted to kindly ask how it looks with the OTA loop issue. Many thanks in advance!

**Comment by jlkalberer** [comment]
There isn't much I can do about the abuse error other than limiting the number of releases to include.

---

I'll try to look into the OTA update in the next few days. I don't think it should be hard to fix.

**Comment by DaliborFarny** [comment]
@john


—
Dalibor Farny

--- original message ---
On Tue, May 22, 2018 at 06:56 pm, <notifications@github.com> John Kalberer wrote:


Cool @AntonPuko was seeing a OTA update loop on one of his devices so there still might be a bug. We'll fix as soon as we have a solid repro.

—

You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---
