### ISSUE TITLE
Fleet auto update not working?

### ISSUE THREAD

**Issue by DaliborFarny** [Brewskey/spark-server#266]
Hello,

I created a product, added a firmware, set it to current:true and added devices. Devices has lower firmware version than current in cloud. No update is triggered, I tried many times with different approach (first add devices, then FW etc..), nothing works. Before I post the complete logs, just asking whether this feature is working?

- all under admin token
- firmware binary compiled with PRODUCT_ID and PRODUCT_VERSION set accordingly.

Thank you!

**Comment by jlkalberer** [comment]
Did you set `current` to true on the firmware?
I assume you compiled in the product ID + product version in your app firmware?

This feature is currently working on my site but I haven't updated to the most recent version of the server.

**Comment by DaliborFarny** [comment]
Hello,


Yes, current: true set, both product version and id set as well.



Will send settings..

—
Dalibor Farny

--- original message ---
> Sat, 26 May at 4:33 PM, <notifications@github.com> wrote:


> Did you set current to true on the firmware?

> I assume you compiled in the product ID + product version in your app firmware?

> This feature is currently working on my site but I haven't updated to the most recent version of the server.

> —

> You are receiving this because you authored the thread.

> Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by jlkalberer** [comment]
Can you send a DB dump of the product tables?

**Comment by DaliborFarny** [comment]
DB attached, I am not sure why there are deleted rows and some old data - I did no manual changes there..


products.db:
{"description":"desc","hardware_version":"v1.5","name":"Zen","platform_id":6,"type":"Consumer","organization":"oE5usm4uNGDGOE3U","slug":"zen-v15","created_at":{"$$date":1527341317822},"product_id":1,"_id":"YUhjwoHmR542DcYG"}
{"description":"desc","hardware_version":"v1.5","name":"Zen","platform_id":6,"type":"Consumer","organization":"oE5usm4uNGDGOE3U","slug":"zen-v15","created_at":{"$$date":1527341317822},"product_id":1,"_id":"YUhjwoHmR542DcYG","id":"YUhjwoHmR542DcYG","config_id":"ZKIoLjluxC4gVIQU"}
{"$$deleted":true,"_id":"YUhjwoHmR542DcYG"}
{"description":"desc","hardware_version":"v1","name":"Sturnus","platform_id":6,"type":"Consumer","organization":"oE5usm4uNGDGOE3U","slug":"sturnus-v1","created_at":{"$$date":1527341507771},"product_id":1,"_id":"9FWk98XmgVe5v0mQ"}
{"description":"desc","hardware_version":"v1","name":"Sturnus","platform_id":6,"type":"Consumer","organization":"oE5usm4uNGDGOE3U","slug":"sturnus-v1","created_at":{"$$date":1527341507771},"product_id":1,"_id":"9FWk98XmgVe5v0mQ","id":"9FWk98XmgVe5v0mQ","config_id":"szaJgEf9ZbupR223"}
{"description":"desc","hardware_version":"v1.5","name":"Zen","platform_id":6,"type":"Consumer","organization":"oE5usm4uNGDGOE3U","slug":"zen-v15","created_at":{"$$date":1527341517767},"product_id":2,"_id":"tWLJS9zpeYCpwceJ"}
{"description":"desc","hardware_version":"v1.5","name":"Zen","platform_id":6,"type":"Consumer","organization":"oE5usm4uNGDGOE3U","slug":"zen-v15","created_at":{"$$date":1527341517767},"product_id":2,"_id":"tWLJS9zpeYCpwceJ","id":"tWLJS9zpeYCpwceJ","config_id":"ZREfa6vChuJfzOu4"}


productConfigs.db
{"org_id":"oE5usm4uNGDGOE3U","product_id":"CIjgZaXH7nknvmFa","_id":"1Y8YUwdCgSCb3vxn"}
{"org_id":"oE5usm4uNGDGOE3U","product_id":"fWjWLfkbBXEFrTAL","_id":"wkehzkD7j5P2qch7"}
{"org_id":"oE5usm4uNGDGOE3U","product_id":"YUhjwoHmR542DcYG","_id":"ZKIoLjluxC4gVIQU"}
{"org_id":"oE5usm4uNGDGOE3U","product_id":"9FWk98XmgVe5v0mQ","_id":"szaJgEf9ZbupR223"}
{"org_id":"oE5usm4uNGDGOE3U","product_id":"tWLJS9zpeYCpwceJ","_id":"ZREfa6vChuJfzOu4"}

productDevices.db
{"denied":false,"development":false,"deviceID":"1d002c000547343339373536","lockedFirmwareVersion":null,"productID":2,"quarantined":false,"_id":"OpNI3v4WzzlPCShh"}
{"denied":false,"development":false,"deviceID":"250041000b47353137323334","lockedFirmwareVersion":null,"productID":2,"quarantined":false,"_id":"VVvNVIcdH2qB3cqn"}
{"denied":false,"development":false,"deviceID":"3f003c000447343232363230","lockedFirmwareVersion":null,"productID":2,"quarantined":false,"_id":"aooCOiYOSGzF27Zj"}
{"denied":false,"development":false,"deviceID":"43002d001447343432313031","lockedFirmwareVersion":null,"productID":2,"quarantined":false,"_id":"HPnf9qasyBqlSCVj"}
{"denied":false,"development":false,"deviceID":"43002d001447343432313031","lockedFirmwareVersion":14,"productID":2,"quarantined":false,"_id":"HPnf9qasyBqlSCVj","id":"HPnf9qasyBqlSCVj"}
{"$$deleted":true,"_id":"HPnf9qasyBqlSCVj"}
{"$$deleted":true,"_id":"OpNI3v4WzzlPCShh"}
{"$$deleted":true,"_id":"aooCOiYOSGzF27Zj"}
{"$$deleted":true,"_id":"VVvNVIcdH2qB3cqn"}
{"denied":false,"development":false,"deviceID":"43002d001447343432313031","lockedFirmwareVersion":null,"productID":2,"quarantined":false,"_id":"6u8Q524Jecsoz034"}
{"$$deleted":true,"_id":"6u8Q524Jecsoz034"}



productFirmware.db (deleted data section)
{"current":"true","data":{"type":"Buffer","data":},"device_count":0,"name":"13.bin","product_id":2,"size":49044,"version":13,"updated_at":{"$$date":1526486654835},"_id":"GE2xhQQQhrz1uIvv","id":"GE2xhQQQhrz1uIvv"}
{"current":"true","data":{},"device_count":0,"name":"12.bin","product_id":2,"size":43216,"version":12,"updated_at":{"$$date":1523449591083},"_id":"j7QoHQ2nEcPskGjz","id":"j7QoHQ2nEcPskGjz"}
{"current":"true","data":{},"description":"FW14Desc","device_count":0,"name":"14.bin","product_id":2,"size":53364,"title":"FW14","version":14,"updated_at":{"$$date":1527341534637},"_id":"OCRmGKpTJvqK3Qv3"}
{"$$deleted":true,"_id":"GE2xhQQQhrz1uIvv"}
{"$$deleted":true,"_id":"j7QoHQ2nEcPskGjz"}
{"$$deleted":true,"_id":"OCRmGKpTJvqK3Qv3"}

**Comment by jlkalberer** [comment]
Hmm... looks like there is a bug when updating `current`.  I see three rows in `productFirmware` where `current == true`. We should handle this for you in the API but maybe you can try setting two of those to false.

I'll see if I can figure out the bug itself

**Comment by jlkalberer** [comment]
Yeah, I don't see any code where we update the old items to `current = false` when creating/updating another ProductFirmware.

cc: @AntonPuko

**Comment by DaliborFarny** [comment]
I cleared the product database completely, starting from scratch, but no luck. I see the spark-server/firmware_product_update (or how it is called) being triggered, but the actual flash doesnt happen. Will try tomorrow with more devices and clean db again. What triggers the update, setting current to true?

—
Dalibor Farny

--- original message ---
> Sat, 26 May at 9:41 PM, <notifications@github.com> wrote:


> Hmm... looks like there is a bug when updating current. I see three rows in productFirmware where current == true. We should handle this for you in the API but maybe you can try setting two of those to false.

> I'll see if I can figure out the bug itself

> —

> You are receiving this because you authored the thread.

> Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by jlkalberer** [comment]
Yeah, when `current` is set to true it will try to update.  I'm going to make sure I didn't break anything with the OTA update... :(

**Comment by AntonPuko** [comment]
@DaliborFarny the thing should work now `without` the caveats.

**Comment by DaliborFarny** [comment]
@AntonPuko thanks for quick update, I cleared DB and now I am creating the structure again - I stuck at creating firmware, this call worked before. It complains about the current not defined, I guess it has something in common with recent commit.

Call:
curl -X POST http://api -H 'authorization: Bearer dbaf81908c7b56b9a92b651c9412345' -H 'cache-control: no-cache' -F version=14 -F 'current=false' -F 'title=FW14' -F 'description=FW14Desc' -F 'binary=@/Users/fw.bin'

response:
{"error":"current is not defined","ok":false}

I tried setting current=true, omitting it completely, nothing helps..

**Comment by AntonPuko** [comment]
Ops. Yeah. I'll fix it today

**Comment by AntonPuko** [comment]
try again

**Comment by DaliborFarny** [comment]
@AntonPuko Thank you, now I can upload the firmware and set it to current. This starts firmware OTA on the device and flash successfully.

These steps make the device end in OTA loop again:

Device system is firmware 0.6.2, it has firmware version 14, which is also the latest one in cloud, set to current.
Then I create firmware version 15, which is compiled against 0.6.3. I put the device offline. I set the firmware v15 current==true. Then I bring the device online again (to see if it gets OTA after comoing online) - now the device ends up in infinite OTA loop.

ERROR: Device.js/22548 on d1000: Client - sendMessage before READY (deviceID=43002d001447343432313089, messageName=UpdateBegin)

Thank you for solving that, I am sure this is the last issue ;)

**Comment by jlkalberer** [comment]
The easiest way for me to solve this is to get the system info from you.

1. Flash the device to 0.6.2 version + v14 firmware
2. Then put the device into listening mode (blinking blue) while plugged in USB.
3. Run `particle serial inspect` (I need this output)
4. Get the device to update to v15 firmware
5. Run `particle serial inspect` again

Thanks!

**Comment by DaliborFarny** [comment]
@jlkalberer Hello, please find the info below:

1. output from device at 0.6.2 with fw v14
Platform: 6 - Photon
Modules
  Bootloader module #0 - version 11, main location, 16384 bytes max size
    Integrity: PASS
    Address Range: PASS
    Platform: PASS
    Dependencies: PASS
  System module #1 - version 108, main location, 262144 bytes max size
    Integrity: PASS
    Address Range: PASS
    Platform: PASS
    Dependencies: PASS
  System module #2 - version 108, main location, 262144 bytes max size
    Integrity: PASS
    Address Range: PASS
    Platform: PASS
    Dependencies: PASS
      System module #1 - version 108
  User module #1 - version 4, main location, 131072 bytes max size
    UUID: CB7B4EE816F96FD009EBF7B2C7AE2698347EC201EE40F4D1B852928D1E8B760C
    Integrity: PASS
    Address Range: PASS
    Platform: PASS
    Dependencies: PASS
      System module #2 - version 108
  empty - factory location, 131072 bytes max size


2. output from device at 0.6.3 with FW v15 (v15 is compiled against 0.6.3)
Platform: 6 - Photon
Modules
  Bootloader module #0 - version 11, main location, 16384 bytes max size
    Integrity: PASS
    Address Range: PASS
    Platform: PASS
    Dependencies: PASS
  System module #1 - version 109, main location, 262144 bytes max size
    Integrity: PASS
    Address Range: PASS
    Platform: PASS
    Dependencies: PASS
  System module #2 - version 109, main location, 262144 bytes max size
    Integrity: PASS
    Address Range: PASS
    Platform: PASS
    Dependencies: PASS
      System module #1 - version 109
  User module #1 - version 4, main location, 131072 bytes max size
    UUID: E09D60FD2942B884E3DBD1834D048DFA7AC8A1ACED5DE0368F578EC4618DE4A9
    Integrity: PASS
    Address Range: PASS
    Platform: PASS
    Dependencies: PASS
      System module #2 - version 109
  empty - factory location, 131072 bytes max size

**Comment by DaliborFarny** [comment]
tried with 5 devices and all behave the same (ending in OTA loop).

**Comment by jlkalberer** [comment]
@DaliborFarny - The issue is that NeDB (default database) was serializing the `Buffer` object when updating `ProductFirmware` which set the firmware data to `[0,0]`.

I have a fix but you should really be using MongoDB for your production server. That will greatly improve performance and allow you to scale past 400 devices.

**Comment by DaliborFarny** [comment]
@jlkalberer thank you, I set up MongoDB, now I need to migrate data from NeDB to MongoDB. I see that there is a script for that, trying to do npm run 'migrate-files-to-mongo', but thats actually looking for folders /users etc in /data dir. Is this supposed for migration of original Spark server json files? Any easy way to migrate current NeDB data to MongoDB? Thanks in advance..

**Comment by jlkalberer** [comment]
We don't have an easy way to migrate original Spark server files.

The `migrate-files-to-mongo` should work for NeDB to MongoDB but I haven't run it in a long time so file paths may have changed.

**Comment by DaliborFarny** [comment]
@jlkalberer @AntonPuko hello, the auto update now seems to be working fine. I just found one situation when the device is not updated. When you add device with firmware with unset PRODUCT_ID, the server ignores it and doesnt update it. This means that when you add fresh Photons to the fleet, they dont get auto update. I am still on NeDB, will switch to Mongo when I find little time.. The auto update is super feature, thank you for it!

**Comment by jlkalberer** [comment]
@AntonPuko - can you fix that when you have some time?

**Comment by AntonPuko** [comment]
@DaliborFarny Try latest. I'm not sure if it doesn't break anything or introduce another infinite loop though, so let us know if it does.

**Comment by DaliborFarny** [comment]
@AntonPuko @jlkalberer I tested the update and it works well. In case of troubles, I will let you know. Thank you!
