### ISSUE TITLE
Error on spark-server update-firmware

### ISSUE THREAD

**Issue by About7Sharks** [Brewskey/spark-server#273]
I'm attempting to install a spark-server on an Ubuntu machine. I've updated node to the current version but the system continues to fail on  "update-firmware"

**Comment by About7Sharks** [comment]
177 verbose stack Error: spark-server@0.1.1 postinstall: `update-firmware`
177 verbose stack Exit status 1
177 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
177 verbose stack     at emitTwo (events.js:126:13)
177 verbose stack     at EventEmitter.emit (events.js:214:7)
177 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
177 verbose stack     at emitTwo (events.js:126:13)
177 verbose stack     at ChildProcess.emit (events.js:214:7)
177 verbose stack     at maybeClose (internal/child_process.js:925:16)
177 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
178 verbose pkgid spark-server@0.1.1
179 verbose cwd /root/spark-server
180 error Linux 4.15.0-22-generic
181 error argv "/usr/bin/node" "/usr/bin/npm" "install" "--unsafe-perm"
182 error node v8.10.0
183 error npm  v3.5.2
184 error code ELIFECYCLE
185 error spark-server@0.1.1 postinstall: `update-firmware`
185 error Exit status 1
186 error Failed at the spark-server@0.1.1 postinstall script 'update-firmware'.
186 error Make sure you have the latest version of node.js and npm installed.
186 error If you do, this is most likely a problem with the spark-server package,
186 error not with npm itself.

**Comment by AntonPuko** [comment]
should be something else in the logs. are you sure you setup `.env` file with your github credentials correctly like it described in [the readme](https://github.com/Brewskey/spark-server#quick-install)?

If you do, could you tell what you did for setup the server step by step.

**Comment by About7Sharks** [comment]
my mistake was naming the .env file. Thanks!
