### ISSUE TITLE
Response timeout for event: spark-server/call_device_function

### ISSUE THREAD

**Issue by jinyangqiao** [Brewskey/spark-server#274]
Hi:
When I request the `/v1/devices/:deviceID/:functionName` interface, I will encounter a response timeout. This will only occur on occasional P1 devices, and after this happens, I only have to power off P1. After powering back, it will return to normal. Pressing the "reset" button and restarting the service will not work.
Requesting other interfaces is normal.

**Comment by jinyangqiao** [comment]
`{
"error": "Response timeout for event: spark-server/call_device_function",
"ok": false
}`
Above is the result of the timeout return.

When the request ends, I only receive the following message by listening to the` v1/events` message:
`event: spark-server/call_device_function/request/2cbfea7f-263b-4a22-bfe9-d180d4380448
data: {"coreid":null,"data":null,"published_at":"2018-08-16T08:10:33.520Z","ttl":60}`

after 15 seconds:
`event: spark-server/call_device_function/response/2cbfea7f-263b-4a22-bfe9-d180d4380448
data: {"coreid":null,"data":null,"published_at":"2018-08-16T08:10:48.522Z","ttl":60}`

At this point, any message that P1 publishes to the cloud is not received.


For normal P1 devices, when the request ends,I will receive the following messages immediately:
`event: spark-server/call_device_function/request/ed48b00a-dfa6-4c62-839e-efe2f04da5a5
data: {"coreid":null,"data":null,"published_at":"2018-08-16T08:13:43.967Z","ttl":60}

event: spark-server/call_device_function/response/ed48b00a-dfa6-4c62-839e-efe2f04da5a5
data: {"coreid":null,"data":null,"published_at":"2018-08-16T08:13:44.138Z","ttl":60}

event: spark-server/get_attributes/request/59cb249f-96b4-4895-aa3c-b7abc9ac03f6
data: {"coreid":null,"data":null,"published_at":"2018-08-16T08:13:44.140Z","ttl":60}

event: spark-server/get_attributes/response/59cb249f-96b4-4895-aa3c-b7abc9ac03f6
data: {"coreid":null,"data":null,"published_at":"2018-08-16T08:13:44.141Z","ttl":60}`

**Comment by AntonPuko** [comment]
Are you sure that it's not your device firmware internal issue? Looks like you call a function on the device which crashes it. Can you confirm that the same issue is not reproducable with particle cloud?

**Comment by jinyangqiao** [comment]
I'm not sure ,I will try with official particle cloud,and check wether this is my device firmware internal issue.
After I find out the reason, I will share.
Thanks very much!

**Comment by jlkalberer** [comment]
@jinyangqiao - did you make this work? Can this issue be closed?

**Comment by jinyangqiao** [comment]
I'm sorry I didn't reply in time!
Because this problem has not been repeated, it can be closed first. Thank you very much!
