### ISSUE TITLE
firmware device counter increases with failed flash attempts

### ISSUE THREAD

**Issue by AntonPuko** [Brewskey/spark-server#276]
Another bug (which might relate to previous) - when you add a device to product, it will be flashed with new firmware - thats OK. But when the firmware is eventually not updated on the device, another flash is triggered (thats OK), but the amount of devices under particular firmware is again increased. We had one device which refuses new firmware (not sure why), but the device counter on the firmware is increased with every attempt to flash it - it reported 1500 devices after overnight attempts to flash the device. Probably duplicates in DB.. Would be nice to check if that particular device ID is already present at this firmware. (c) DaliborFarny

**Comment by jlkalberer** [comment]
Yeah.. I believe a number is just hardcoded there. We should use a query for that number instead of saving the number of devices in a firmware to the DB.

**Comment by jlkalberer** [comment]
This has been fixed in a recent-ish update
