### ISSUE TITLE
Hook for device status change?

### ISSUE THREAD

**Issue by snazzypants** [Brewskey/spark-server#284]
Hi there,

I was wondering if there is a way to hook into the online/offline status of a device, so that the status can be sent to an external database server, for  example.  Basically, if a device goes offline, I'd like to send that over to another server, which can handle logging and notifications.

Thanks!

**Comment by jlkalberer** [comment]
A simple way to do it would using the `events` endpoint. 

If you're using `spark-server` as a dependency for your project, there should be a way to add a callback any time events trigger. You'd just need to get an instance of `EventManager` and call `subscribe`.

**Comment by snazzypants** [comment]
Thanks! Your reply made me realize that I could just create a webhook that listens for events named `spark/status`. Then the webhook just sends over status updates to my database server.

If anyone is wondering, the particle docs have some documentation on [special events](https://docs.particle.io/reference/device-cloud/api/#special-events) (I'm guessing that not all of these are implemented in this fork/vintage of spark-server), and you can utilize these [predefined webhook variables](https://docs.particle.io/reference/device-cloud/webhooks/#pre-defined-variables) to access the variables in the webhook.

**Comment by jlkalberer** [comment]
@snazzypants - I think we support all of those events and variables. The only one I'm not sure about is the `app-hash`
