### ISSUE TITLE
Is there a way to pass the contents of the publish event directly to MQ?

### ISSUE THREAD

**Issue by jinyangqiao** [Brewskey/spark-server#286]
Hi:
I want to pass the contents of the publish event directly to MQ and I don't want to deal with it by subscription,because I found that, the memory consumed by the program will always increase(about 150 devices,and 3 messages per second per device).
So is there a way to pass the contents of the publish event directly to MQ without subscribing?
Thanks very much!

**Comment by jlkalberer** [comment]
I haven't actually used MQ -- it was a PR from someone else.

What do you mean by "subscription"?
Also, you're seeing the memory increase over time? If so we have a memory leak and should probably fix that.

**Comment by jinyangqiao** [comment]
In order to hand the published message to MQ, I subscribed to all events via `v1/events/*` and then handed the subscribed message to MQ.
When the number of the P1 and messages per second increases,the memory consumed by the program will increase over time.

**Comment by jlkalberer** [comment]
Someone did something similar to this using webhooks. If there is a web API on MQ you could do it that way.

Otherwise you need to subscribe. You are only doing one subscription right? That will get all messages from all devices. I'm not sure why you are seeing a memory increase from subscribing to the events.

**Comment by jinyangqiao** [comment]
I tested by the particle-collider on your giyhub [https://github.com/Brewskey/particle-collider],
In order for each virtual device to send more data to the spark-server every second, I modified the program slightly.
Yes,I only do one subscription,but I don't use a web API on MQ, 
I modified the code of the spark-server to process the subscription message and then handed it to MQ for processing.

**Comment by jlkalberer** [comment]
I think we would need to run a node profiler in order to find the bug but I don't have time to do it now.

I'm not sure when I'll get to #287 but it won't be soon.

**Comment by jinyangqiao** [comment]
OK,I see.
Thanks very much,and I will also check my own question, perhaps because I modified the code to cause this problem.

**Comment by jlkalberer** [comment]
I think #287 covers any bug here.
