### ISSUE TITLE
Function call returns error when firmware function returns zero

### ISSUE THREAD

**Issue by rkast** [Brewskey/spark-server#290]
Some of my device firmware return a zero in a cloud function call. These calls would return from the API with a 'Failed to load resource: the server responded with a status of 400 (Bad Request)', despite having the device respond correctly to the cloud function call.

**Comment by jlkalberer** [comment]
So the device returns `0` and the server throws an exception?

**Comment by rkast** [comment]
Correct

**Comment by jlkalberer** [comment]
Ok, so if your device returns a non-zero it works fine? I'm just trying to zero in on the bug.

**Comment by rkast** [comment]
Yep, I could get you more details on it tomorrow if you need.

**Comment by jlkalberer** [comment]
@rkast - there should be an exception in the 400 response. Can you get that for me?

You should be able to call the API like this - https://docs.particle.io/reference/device-cloud/api/#call-a-function
You can see the `access_token` when the server starts up.

**Comment by jlkalberer** [comment]
@rkast - did you resolve this?
