### ISSUE TITLE
Throws error on starting spark-server

### ISSUE THREAD

**Issue by Sarveshwar20** [Brewskey/spark-server#292]
attaching the error i get when executing 'npm start' on my device.

![screenshot 2019-02-21 at 3 56 58 pm](https://user-images.githubusercontent.com/47527373/53162167-75210700-35f1-11e9-8203-6ee860087243.png)

**Comment by jlkalberer** [comment]
I'm not sure if it matters or not but we are using `yarn` for this project.

I'll have time to check this out over the weekend and I'll let you know what's going on. To me, it looks like the node lock file hasn't been updated and you're missing some modules. I'd start by:
1. Delete the npm lock file
2. Run `npm install`

If that doesn't work, maybe try installing `yarn` and running with that.
