### ISSUE TITLE
Is there a renamed implementation of Particle.subscribe(particle/device/name); ?

### ISSUE THREAD

**Issue by mrferrar** [Brewskey/spark-server#298]
I have noticed there is a useful feature on Particle's server where a photon call of `Particle.subscribe("particle/device/name", ...);` triggers a `particle/device/name` event that the device can subscribe to in order to get it's server-assigned name.
Does this feature have a different trigger on this server?

**Comment by jlkalberer** [comment]
It does but it's using the legacy command for it -- `spark/device/name`
I haven't updated any of the commands since they started porting them to be "particle" vs "spark"

**Comment by mrferrar** [comment]
I did try that, though annoyingly the photons seem unable to properly subscribe to any events with the 'spark' prefix. Thanks for confirming.

**Comment by jlkalberer** [comment]
Ok -- I can put out an update to fix this.

**Comment by jlkalberer** [comment]
Ok -- this *should* be fixed. I didn't test it.

Make sure you update the node modules in order to get the latest version of spark-protocol

**Comment by mrferrar** [comment]
That worked, thank you!
