### ISSUE TITLE
socket timeout error

### ISSUE THREAD

**Issue by durielz** [Brewskey/spark-server#55]
If my device disconnects from network i get:
`Caught exception: TypeError: Cannot read property 'message' of undefined TypeError: Cannot read property 'message' of undefined
    at Socket.<anonymous> (/node_modules/spark-protocol/lib/clients/Device.js:175:66)
`

changing in client/Device.js in protocol the line 134 from
`error: Error): void => this.disconnect(`socket timeout ${error.message}`),`
to
`error: Error): void => this.disconnect(`socket timeout ${error}`),`
then i have the correct disconnect message

**Comment by AntonPuko** [comment]
Thanks, will be fixed in this PR: https://github.com/Brewskey/spark-protocol/pull/15
