### ISSUE TITLE
about events

### ISSUE THREAD

**Issue by durielz** [Brewskey/spark-server#77]
hi guys i was playing with events and i would like to share with you how they should work for me:

1. GET /v1/events should return all public events (from all devices) and private events from devices owned by me
2. GET /v1/devices/events should return all public and private events from my devices only
3. GET /v1/devices/:deviceId/events should return all public and private events for a specific device if the device is owned by me otherwise only the public events

Is that the way you are going to implement them?

In your version i have:
1. GET /v1/events return all public and private events for all devices
2. GET /v1/devices/events doesn't return special private events like status / flash
3. GET /v1/devices/:deviceId/events return only events from devices i own

**Comment by jlkalberer** [comment]
Yeah, I think we will make them work like the normal cloud.

Right now I'm filtering out all private events... 
https://github.com/Brewskey/spark-protocol/blob/dev/src/server/DeviceServer.js#L353-L356

I wasn't sure which events should be visible when you call those APIs. I know some should be hidden though. You have any idea?

**Comment by jlkalberer** [comment]
@AntonPuko - do you want to take care of this one?
I see a TODO here that deals with it I think:
https://github.com/Brewskey/spark-protocol/blob/dev/src/server/DeviceServer.js#L122-L128

**Comment by durielz** [comment]
Well, all the events that start with 'spark' should be hidden except for the special events https://docs.particle.io/reference/api/#special-events

Custom public and private events should be shown following the rules above

**Comment by jlkalberer** [comment]
Awesome.  I have a large diff going out that is removing todos and I just disable the filter for now..

I'll work on this next and add the filter back in.

**Comment by jlkalberer** [comment]
Also, @durielz I can send you an invite to our slack channel if you want.  It might help with some of this communication.

**Comment by durielz** [comment]
Ok!
Il giorno sab 14 gen 2017 alle 21:38 John Kalberer <notifications@github.com>
ha scritto:
