### ISSUE TITLE
OAuth...

### ISSUE THREAD

**Issue by jlkalberer** [Brewskey/spark-server#82]
Have fun with this one @AntonPuko

**Comment by harrisonhjones** [comment]
Should OAuth really be implemented at the Spark Server level? The original spark-server didn't really support access tokens. How are y'all handing them?

**Comment by jlkalberer** [comment]
The original server did support tokens + OAuth but not very well.

OAuth should definitely be at the server level and not the protocol level.  The protocol package is mostly for running COAP.

That said, the way we will implement COAP will allow you to optionally turn it off or use two-legged OAuth so you can use a different server for authentication.
