### ISSUE TITLE
Server hangs if URL for new webhook does not respond

### ISSUE THREAD

**Issue by wdimmit** [Brewskey/spark-server#89]
If a webhook is created and the selected URL times out, the server hangs completely with the following error:

`uncaughtException { message: 'connect ECONNREFUSED 67.161.118.40:3000',
  stack: 'Error: connect ECONNREFUSED 67.161.118.40:3000\n    at Object.exports._errnoException (util.js:1022:11)\n    at exports._exceptionWithHostPort (util.js:1045:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)' }
[nodemon] app crashed - waiting for file changes before starting...`

**Comment by AntonPuko** [comment]
this related with https://github.com/Brewskey/spark-server/issues/80, will be fixed soon.

**Comment by AntonPuko** [comment]
for now you can comment https://github.com/Brewskey/spark-server/blob/dev/src/managers/WebhookManager.js#L161 this line

**Comment by jlkalberer** [comment]
Can this be closed?

**Comment by AntonPuko** [comment]
yes
