### ISSUE TITLE
particle subscribe fail

### ISSUE THREAD

**Issue by AntonPuko** [Brewskey/spark-server#94]
`particle subscribe` fails when we'are trying to subscribe to eventNames with `/`.
We get 404 error from api.

`particle subscribe foo/bar` send request to `http://localhost:8080/foo/bar` but the controller handles only `http://localhost:8080/:eventPrefix`

**Comment by jlkalberer** [comment]
for the subscribe route you just need to change it to `/v1/subscribe/:eventPrefix*` and that should fix it.

**Comment by AntonPuko** [comment]
ah..didn't know about that option. nice
